name: Deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install
        run: yarn
      - name: Build
        run: npx ng build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install
        run: yarn global add firebase-tools
      - name: Deploy
        run: firebase deploy --project 'etherio-pay' --token '${{ secrets.FIREBASE_TOKEN }}'
