name: Deploy
on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Installing Dependencies
      run: npm install
    - name: Build Angular Project
      run: npx ng build
    - name: Deploy to Firebase Hosting
      run: npx firebase deploy --project etherio-pay --token '${{ secrets.FIREBASE_TOKEN }}'

